### ISSUE TITLE
Question about the examples - SIGTERM vs SIGINT

### ISSUE THREAD

**Issue by papb** [ehmicky/human-signals#1]
From the [examples](https://github.com/ehmicky/human-signals#example):

```js
console.log(signalsByName.SIGTERM)
// {
//   name: 'SIGINT',
//   number: 2,
//   description: 'User interruption with CTRL-C',
//   supported: true,
//   action: 'terminate',
//   forced: false,
//   standard: 'ansi'
// }
```

Why is `signalsByName.SIGTERM.name === "SIGINT"`? This is surprising to me...

-------

By the way thanks for the great work on all your repositories :) I really like your work.

**Comment by ehmicky** [comment]
Hi @papb,

Thanks a lot for pointing this out! This is a typo. Fixed in f59a9d704d11622020dbf66c9f89bfbbdec22930

> By the way thanks for the great work on all your repositories :) I really like your work.

Thanks a lot, this cheered up my day :)
