### ISSUE TITLE
remove the useless sourcemap url in file end

### ISSUE THREAD

**Issue by tjx666** [ehmicky/human-signals#15]
### Guidelines

- [X] Please search other issues to make sure this bug has not already been reported.
- [X] If this is related to a typo or the documentation being unclear, please click on the relevant page's `Edit` button (pencil icon) and suggest a correction instead.

### Describe the bug

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/226135276-e573eb51-a79d-41b0-a844-fe13053a13e1.png">

### Steps to reproduce

just install the module and open `build/src/core.js` file, check the file end

### Configuration

no

### Environment

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 157.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 18.15.0 - ~/Library/Caches/fnm_multishells/5372_1679169655890/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/5372_1679169655890/bin/yarn
  npm: 9.6.2 - ~/Library/Caches/fnm_multishells/5372_1679169655890/bin/npm
Browsers:
  Chrome: 111.0.5563.64
  Chrome Canary: 113.0.5660.0
  Firefox: 109.0.1
  Firefox Developer Edition: 111.0
  Safari: 16.3

### Pull request (optional)

- [X] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @tjx666,

Thanks for reporting this bug. This should now be fixed in [`4.3.1`](https://github.com/ehmicky/human-signals/releases/tag/4.3.1).
