### ISSUE TITLE
Why `?` in `signalsByName` type definition

### ISSUE THREAD

**Issue by FelixZY** [ehmicky/human-signals#23]
https://github.com/ehmicky/human-signals/blob/0f9928856970ba55d64e887ffb1246dce2d3df55/src/main.d.ts#L137

The `?` causes TS warnings:

![Screenshot from 2024-08-03 02-06-12](https://github.com/user-attachments/assets/193edbc5-b759-4421-83d2-63699832b3bb)

Is this a valid warning or could the `?` in the type definition be removed?

**Comment by ehmicky** [comment]
Hi @FelixZY,

No there is not! Would you like to send a PR to fix the types and the type tests?

**Comment by ehmicky** [comment]
@all-contributors Please add @FelixZY for code, test.

**Comment by ehmicky** [comment]
This was released in [`8.0.0`](https://github.com/ehmicky/human-signals/releases/tag/8.0.0).
Thanks for your contribution @FelixZY!

**Comment by FelixZY** [comment]
My pleasure. Thank you for the quick release!
